# Use the official Nginx base image
FROM nginx:latest

# Copy custom Nginx configuration to the container
COPY /conf/nginx.conf /etc/nginx/conf.d/thinkslab_ai.conf   

# Expose port 80
EXPOSE 80

# Start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]
